	<meta name="HandheldFriendly" content="True">
	<meta name="MobileOptimized" content="320">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1, user-scalable=no, minimal-ui">

	<link rel="canonical" href="http://www.example.com/">

	<!-- Add to homescreen for Chrome on Android -->
	<!--
	<meta name="mobile-web-app-capable" content="yes">
	-->

	<!-- For iOS web apps. Delete if not needed. https://github.com/h5bp/mobile-boilerplate/issues/94 -->
	<!--
	<meta name="apple-mobile-web-app-capable" content="yes">
	<meta name="apple-mobile-web-app-status-bar-style" content="black">
	<meta name="apple-mobile-web-app-title" content="">
	-->

		<!-- Touch Icons -->
	<link rel="apple-touch-icon-precomposed" href="/favicons/152x152.png" sizes="152x152"> <!-- iPad retina touch icon (iOS7) -->
	<link rel="apple-touch-icon-precomposed" href="/favicons/144x144.png" sizes="144x144"> <!-- iPad retina touch icon (iOS6) -->
	<link rel="apple-touch-icon-precomposed" href="/favicons/120x120.png" sizes="120x120"> <!-- iPhone retina touch icon (iOS7) -->
	<link rel="apple-touch-icon-precomposed" href="/favicons/114x114.png" sizes="114x114"> <!-- iPhone retina touch icon (iOS6) -->
	<link rel="apple-touch-icon-precomposed" href="/favicons/72x72.png" sizes="72x72"> <!-- 1st/2nd gen iPads -->
	<link rel="apple-touch-icon-precomposed" href="/favicons/57x57.png"> <!-- web browsers that support png favicon -->

	<!-- Favicon PNGs -->
	<link rel="icon" type="image/png" href="/favicons/228x228.png" sizes="228x228"> <!-- Opera Coast icon -->
	<link rel="icon" type="image/png" href="/favicons/195x195.png" sizes="195x195"> <!-- Opera Speed Dial icon -->
	<link rel="icon" type="image/png" href="/favicons/128x128.png" sizes="128x128"> <!-- Chrome Web Store icon -->
	<link rel="icon" type="image/png" href="/favicons/96x96.png" sizes="96x96"> <!-- GoogleTV icon -->
	<link rel="icon" type="image/png" href="/favicons/32x32.png" sizes="32x32"> <!-- web browsers that support png favicon -->

	<!-- Favicon ICO -->
	<!-- <link rel="shortcut icon" href="http://local.voya.com.10.118.0.32.xip.io/favicon.ico?v=2"> -->

	<!-- IE10 Metro tile for pinned site -->
	<meta name="msapplication-TileColor" content="#FFFFFF">
	<meta name="msapplication-TileImage" content="/favicons/144x144.png">
	<meta name="msapplication-square70x70logo" content="/favicons/70x70.png"/>
	<meta name="msapplication-square150x150logo" content="/favicons/150x150-wide.png"/>
	<meta name="msapplication-wide310x150logo" content="/favicons/310x150.png"/>
	<meta name="msapplication-square310x310logo" content="/favicons/310x310.png"/>

	<link href="css/global.css" rel="stylesheet" type="text/css" />

	<script src="bower_components/modernizr/modernizr.js"></script>
	<script src="bower_components/requirejs/require.js"></script>
	<script src="bower_components/jquery/jquery.min.js"></script>

